# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pypy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Autodoc Gen"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - name: Checkout Codes
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: anaconda, conda-forge

    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH

    - name: Install Dependencies for Pygame in pypy
      run: |
        sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev -y

    - name: Install dependencies
      run: |
        conda install -c conda-forge pypy
        conda install pytest
        conda install scipy
        conda install numpy
        conda install matplotlib
        conda install dill
        conda install multiprocess
        pip install PettingZoo
        pip install gym==0.25.0
        pip install pyglet
        pip install pymunk
        pip install pygame
        pip install sphinx
        pip install sphinx-rtd-theme
        pip install sphinx-copybutton
        conda install hyperopt
        conda install optuna
        pip install transformations
        conda install river
        conda install openml

    - name: Check Python
      run: which python
        
    - name: Test with pytest
      run: |
        pypy3 -m pytest --ignore=src/mlpro/rl/pool/envs/ur5jointcontrol/src/ --ignore=src/mlpro/rl/pool/envs/multigeorobot/src/
